# .github/workflows/ci.yml
name: CI

# Run on pushes and PRs against main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install pnpm (since this template uses pnpm)
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8       # or whatever pnpm version you want

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # 4. Build the project
      - name: Build
        run: pnpm run build
